# Generated by Django 3.2.7 on 2021-09-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterreadings',
            old_name='metereRadings',
            new_name='metRadings',
        ),
    ]
